---
all:
  children:
    ICG:
      hosts:
        srv-icg-01:
          ansible_host: srv-icg-01.dmz.igelcommunity.com
    UMS:
      hosts:
        srv-ums-01:
          ansible_host: srv-ums-01.lan.igelcommunity.com
