@startuml name IGEL-Ansible

frame DMZ {

  object icg {
    hostname: srv-icg-01
    function: ICG, Filetransfer
    IP public: 23.236.62.147
    IP private: 192.168.2.1
  }

}

frame LAN {

  object ums {
    hostname: srv-ums-01
    function: UMS
    IP private: 192.168.1.1
  }

  object nas {
    hostname: srv-nas-01
    function: Backup
    IP private: 192.168.1.2
  }

  object Device_LAN {
    function: IGELOS
  }

}

frame WAN {

  object Device_WAN {
    function: IGELOS
  }

}


WAN .down. DMZ
DMZ .down. LAN

ums -up-> icg
ums -down-> nas
ums -down-> Device_LAN
Device_LAN -up-> ums
Device_LAN -up-> icg
Device_WAN -down-> icg

@enduml