@startuml name IGEL-Ansible

frame DMZ {

  object icg {
    hostname: srv-icg-01
    function: ICG, Filetransfer
    FQDN public: icg.igelcommunity.com
    FQDN private: srv-icg-01.dmz.igelcommunity.com
  }

}

frame LAN {

  object ums {
    hostname: srv-ums-01
    function: UMS
    FQDN private: srv-ums-01.lan.igelcommunity.com
  }

  object nas {
    hostname: srv-nas-01
    function: Backup
    FQDN private: srv-nas-01.lan.igelcommunity.com
  }

  object Device01 {
    function: IGELOS
  }

}

frame WAN {

  object Device02 {
    function: IGELOS
  }

}


WAN .down. DMZ
DMZ .down. LAN

ums -up-> icg
ums -down-> nas
ums -down-> Device01
Device01 -up-> ums
Device01 -up-> icg
Device02 -down-> icg

@enduml