@startuml name IGEL-Ansible

frame DMZ #Orange{

  object icg {
    hostname: srv-icg-01
    function: ICG, Filetransfer
    FQDN public: icg.igelcommunity.com
    FQDN private: srv-icg-01.dmz.igelcommunity.com
  }

}

frame LAN #LightGreen {

  object ums {
    hostname: srv-ums-01
    function: UMS
    FQDN private: srv-ums-01.lan.igelcommunity.com
  }

  object nas {
    hostname: srv-nas-01
    function: Backup
    FQDN private: srv-nas-01.lan.igelcommunity.com
  }

  object Device01 {
    function: IGELOS
  }

}

frame WAN #Red {

  object Device02 {
    function: IGELOS
  }

}

map Communication {
  22 TCP                => SSH
  8443 TCP              => Filetransfer to Devices; Communication to ICG
  8444 TCP              => HTTPS
  30001 TCP             => Devices contacting UMS
  30005 TCP/UDP         => BC from UMS to Devices; Devices respond to BC from UMS
  30022 TCP             => Secure Terminal to Devices
}

Communication .left[#white]. WAN
WAN .down[#white]. DMZ
DMZ .down[#white]. LAN

Device02 -down-> icg: **8443 TCP**
Device02 -down-> icg: **8444 TCP**
ums -up-> icg: **8443 TCP**
ums -up-> icg: **22 TCP**
ums -right-> nas: **22 TCP**
Device01 -up-> ums: **8443 TCP**
Device01 -up-> ums: **30001 TCP**
Device01 <-up-> ums: **30005 TCP/UDP**
Device01 <-up- ums: **30022 TCP**
Device01 -up-> icg: **8444 TCP**


@enduml